### ISSUE TITLE
Be able to provide connector default meta-data

### ISSUE THREAD

**Issue by nikku** [camunda/connector-sdk#12]
__What should we do?__

Be able to provide connector meta-data in a structured manner so that run-times can consume it (to load fetched variables / name / type).

__Describe the solution you'd like__

This could work by annotating a connector function to define meta data:

```java
@OutboundConnector(
        name = "amqp",
        taskType = "io.camunda.community:amqp:1",
        inputVariables = {"destinationName","destinationType","username","password"})
class MyConnectorFunction implements ConnectorFunction {
    ...
}
```

* [x] add `OutboundConnector` annotation https://github.com/camunda/connector-sdk/pull/104
* [ ] pick up `OutboundConnector` annotation meta-data in jobworker run-time https://github.com/camunda/connector-sdk/pull/111

__Why should we do it?__

Be able to parse default configuration from connector functions so they can be consumed safely , i.e. in a run-time that batch-executes a number of them.

**Comment by nikku** [comment]
[An instance](https://camunda.slack.com/archives/C02JLRNQQ05/p1660954753577799?thread_ts=1660754058.854809&cid=C02JLRNQQ05) where a user is struggling with this.

**Comment by nikku** [comment]
@igpetrov @tmetzke Right now we parse outbound connectors (to be registered run with job-worker built-in runtime) from environment variables.

The user is in full control of which connector to run and how to configure it (https://github.com/camunda/connector-sdk/tree/main/runtime-job-worker#running-connector-functions). You could argue that _at least_ `inputVariables` are hard-coded in the connector (shall always be fetched from the annotation if present). What about the other ones?

* Shall we auto-discover connectors on the classpath (+ configure them automatically?). We could allow users to opt-out but auto-discovery (via SPI) would be the default
* _OR_ Shall the user still explicitly set which connectors to execute, i.e. via a `ZEEBE_CONNECTORS=io.camunda.Foo:1,io.camunda.Echo:10` environment variable => Backwards compatible + reads existing environment variables, too, if present, to override provided defaults

To aid migration I'd print a warning if the job worker does not define meta-data via `@OutboundConnector` annotation.

**Comment by igpetrov** [comment]
Thank you, @nikku for putting it all together. I am a bit of out of the context but about how job worker actually works.
Assuming, Job Worker can contain multiple `@OutboundConnector`s and the goal it to target self-managed platforms.

I am looking from an analogy for Spring MVC - where a controller (`@Controller`), registered at `DispatcherServlet` and each method represents a specific endpoint (`@RequestMapping`).

[not relevant to your question] Firstly, I don't really get why should we have `inputVariables` as a part of `@OutboundConnector`. I would rather go for field level annotation (e.g., `@InputVariable`). Was this a design decision?

As a customer, I would certainly prefer autoconfiguration. The question is though, how many pieces of configuration do we need to provide to make the actual connector running - API keys, endpoints properties? This is something that I seem to miss in my head. Example. Say, I have Google Drive on my local instance. Do I need to provide an API key via Modeler or would I just better get it from the path variable? Or, what if I would like to extend it to new use-case, say local FTP backup - how do I hardcode my FTP login/pass? If we anticipate multiple pieces of configuration, it could decline all benefits of autoconfiguration.

The explicit way on the other hand is more flexible but brings extra boiler plate code.

Returning to my Spring MVC analogy. Maybe we can do something that is both option 1 and option 2 you proposed. Spring MVC by default provides dispatcher servlet, rendering engines, controllers support - all annotation driven. However, if you don't like the default configuration, feel free to implement your own and register by hand. But I am not sure how much of overhead would it take.

Example: you can write `@Controller` but you can also write `class MyController extends MultiActionController` and register it in respective xmls. Same with `DispatcherServlet` - Spring provides it by default but if you want to configure custom properties - feel free to create (and register) your own.

Maybe we can have a short meeting in upcoming days to make sure we understand each other.

**Comment by tmetzke** [comment]
## Use Cases

So, what are the use cases we want to support? (This is mainly for me to get an idea but maybe it helps someone else, too).

1. Simple default case: 
   * Connector has the annotation and SPI
   * SM runtime + Connector are on classpath
   * => pick up everything from annotation
1. Override job type: 
   * Connector has the annotation and SPI
   * SM runtime + Connector are on classpath
   * ENV variable `ZEEBE_CONNECTOR_SLACK_TYPE=io.camunda:slack:3`
   * => pick up everything from annotation, override job type with `io.camunda:slack:3`
1. Override name:
   * Connector A has the annotation (name="slack") and SPI, function name `org.company1.connector.SlackFunction`
   * Connector B has the annotation (name="slack") and SPI, function name `org.company2.connector.slack.SlackFunction`
   * SM runtime + Connector A + Connector B are on classpath
   * ENV variable `ZEEBE_CONNECTOR_SLACK1_FUNCTION=org.company1.connector.SlackFunction`
   * ENV variable `ZEEBE_CONNECTOR_SLACK2_FUNCTION=org.company2.connector.slack.SlackFunction`
   * => pick up everything from annotations, override names with `slack1` and `slack2` (function name should match the class we found the annotation on)
 1. Override variables: I don't see any use for that currently, but maybe there is. We can simply ignore this ENV var for now, maybe. I am also fine with allowing this (so we don't need to add this later on).
 1. No SPI: _do we want to support this?_
    * Connector has the annotation (but no SPI)
    * SM runtime + Connector are on classpath
    * => nothing is picked up
1. No SPI but ENV vars: _do we want to support this?_
   * Connector has the annotation (but no SPI)
   * SM runtime + Connector are on classpath
   * ENV variable `ZEEBE_CONNECTOR_SLACK_FUNCTION=io.camunda.connector.slack.SlackFunction`
   * => pick up everything from annotation
 1. Manual configuration of Connectors:
   * Connector A has the annotation (name="slack") and SPI, function name `org.company1.connector.SlackFunction`
   * Connector B has the annotation (name="sendgrid") and SPI, function name `org.company1.connector.SendgridFunction`
   * SM runtime + Connector A + Connector B are on classpath
   * ENV var `ZEEBE_CONNECTORS=org.company1.connector.SlackFunction`
   * => only pick up "slack", but not "sendgrid"

## Loading mechanism

Not sure this covers everything, but maybe the following mechanism:

1. Load connector functions
   1. ENV var `ZEEBE_CONNECTORS` exists (_should we rename this to something non-Zeebe-related, btw?_)
   => load the configured function classes, fetch their annotations
   1. Otherwise, load all SPI implementations of `OutboundConnectorFunction`
1. ENV var `ZEEBE_CONNECTOR_<NAME>_FUNCTION` exists
=> override the "name" of the associated Connector configuration
1. ENV var `ZEEBE_CONNECTOR_<NAME>_TYPE` exists
=> override the "type" property of the associated Connector configuration (with the same "name")

This supports use cases 1, 2, 3, 5, 6, 7

Anything else that we need?

**Comment by nikku** [comment]
Decided:

* Auto discovery at the core
* Warn on non-existing annotation (meta-data)
* Override via ENV variables every aspect of a connector
* ENV prefix is `CONNECTORS`

----

* ~~Be able to override individual connector to run (whitelist connectors via `CONNECTORS_ALLOWLIST=...` that are picked up)~~
* ~~Expose retrival utility + connectorConfig as public API~~

    ```java
    var zeebeClient = ZeebeClient.newClientBuilder().build();
    var config = ConnectorUtil.getOutboundConnectorConfig(SlackFunction.class);

    zeebeClient.newWorker()
        .jobType(config.getJobType())
        .handler(new ConnectorJobHandler(new SlackFunction()))
        .name(config.getName())
        .fetchVariables(config.getInputVariables())
        .open();
    }
    ```
    
----

* Document in https://github.com/camunda/camunda-platform-docs/pull/1255

----

**Comment by nikku** [comment]
@tmetzke to simplify this implementation (which will otherwise be a mess) I propose the following:

* Either the user specifies overrides via environment variables / properties -> we take these, consistently (+ make variables optional / read these from annotatoin if not provided)
* _OR_ she does nothing, and the default behavior kicks in (auto-discovery)
* There is no mode in the middle

==> That simplifies our implementation + documentation efforts, and our users are either in full control or it just works mode.

**Comment by igpetrov** [comment]
@nikku, both approaches make sense. In my opinion we should give customers flexibility therefore I would vote for option 1 - env variables override.

**Comment by tmetzke** [comment]
So, what's the implication? What is not possible anymore with this new approach?
Plus, could you detail a bit on what makes the currently defined approach too complicated to implement?
I just want to understand why we want to derive from it. 🙂

**Comment by nikku** [comment]
@tmetzke The override logic makes it hard to implement. 

Also conceptionally it is not easy for me as a user to comprehend: If I override I need to understand what is the _key_ that I use to get hold of the existing configuration. Right now it is `TYPE`, but you propose `FUNCTION` to be the identifying element. If it is function though I cannot run a connector under two different types (i.e. spawn slack up using an old and new configuration:

```
ZEEBE_CONNECTOR_SLACK_TYPE=io.camunda:slack:1
ZEEBE_CONNECTOR_SLACK_FUNCTION=io.camunda.connector.slack.SlackFunction
ZEEBE_CONNECTOR_SLACK_NEW_TYPE=io.camunda:slack:2
ZEEBE_CONNECTOR_SLACK_NEW_FUNCTION=io.camunda.connector.slack.SlackFunction

java -cp 'connector-runtime-job-worker.jar;cloud-connector-slack.jar' \
    io.camunda.connector.runtime.jobworker.Main
```

All of this is solved by operating in two clearly distinguishable modes.

**Comment by tmetzke** [comment]
I see, OK, makes sense to me. 

So, just to make sure I understand this right, let's take this use case

* I have 3 Connectors (slack, sendgrid, rest) on the classpath
* I want to adjust Slack's `type`
* I have to create at least 4 ENV vars
  * CONNECTOR_SENDGRID_FUNCTION=io.camunda.connector.sendgrid.SendgridFunction
  * CONNECTOR_SLACK_FUNCTION=io.camunda.connector.slack.SlackFunction
  * CONNECTOR_HTTP_JSON_FUNCTION=io.camunda.connector.slack.HttpJsonFunction
  * CONNECTOR_SLACK_TYPE=slack

Is that correct? I assume, if I want to override something, I have to define all other Connectors as well? Because that is the "manual mode" then I want to use?

Or do we only NOT auto-discover if there is at least one `CONNECTOR_{NAME}_FUNCTION` ENV var? 🤔

**Comment by nikku** [comment]
> Or do we only NOT auto-discover

We do not auto-discover as soon as there is a single ENV var we recognize, so yes!

**Comment by nikku** [comment]
Please checkout https://github.com/camunda/connector-sdk/pull/111, especially the README changes. If this is a direction we want to go for I#m happy to add some basic test coverage around this.

If not we'd really need to solve the ambiguity issues mentioned (https://github.com/camunda/connector-sdk/issues/12#issuecomment-1254928208).

**Comment by tmetzke** [comment]
I think that's very useful and we can definitely start with this! 👍 
If we need something more convenient (e.g. auto discover plus ENV vars), we can still do that in the future.

**Comment by nikku** [comment]
Documented `@OutboundConnector` annotation + job-worker-runtime behavior via https://github.com/camunda/camunda-platform-docs/commit/0e67e270a3edcc5cd3cc899041475597b01d213f.
