### ISSUE TITLE
Add Configuration facility that allows to run Connectors standalone and within Spring

### ISSUE THREAD

**Issue by berndruecker** [camunda/connector-sdk#269]
Connectors currently are plain Java components, but they will also be run in a Spring runtime. 
They do need configuration, which in plain-Java mode is coming from environment variables (`System.getEnv`). In Spring, this should be delegate to the Spring Environment. 
The same is foreseeable for other injectable beans, especially if we start using Spring components to implement conntecors. 
Also the SecurityProvider might be wired differently in a Spring context (e.g. as it might use the GcpSecretStore)

**Comment by berndruecker** [comment]
- Added configuration options to SDK: https://github.com/camunda/connector-sdk/pull/266
- Use those in HTTP connector - part of: https://github.com/camunda/connector-http-json/pull/177
- Wire it together properly in spring-zeebe: https://github.com/camunda-community-hub/spring-zeebe/pull/264

@igpetrov @tmetzke Happy to walk anybody through those changes - would love to merge them soon.

In essence:

- https://github.com/camunda/connector-sdk/blob/fbacb55c5c08d7e7313552af40090a3357bb4ab7/core/src/main/java/io/camunda/connector/impl/config/ConnectorConfigurationUtil.java allows to query for configuration properties or beans by type
- This is needed, as SPI always creates instances using the default no-arg constructor
- As a default implementation and fallback, System.getEnv is used - or the default beans provided by the connector as config:

```java
public class HttpJsonFunction implements OutboundConnectorFunction {
  static {
    ConnectorConfigurationUtil.addBeanOverwrite(GsonComponentSupplier.gsonInstance());
    ConnectorConfigurationUtil.addBeanOverwrite(
        HttpTransportComponentSupplier.httpRequestFactoryInstance());
    ConnectorConfigurationUtil.addBeanOverwrite(GsonComponentSupplier.gsonFactoryInstance());
  }

  public HttpJsonFunction(String proxyFunctionUrl) {
    this(
        ConnectorConfigurationUtil.getBean(Gson.class),
        ConnectorConfigurationUtil.getBean(HttpRequestFactory.class),
        ConnectorConfigurationUtil.getBean(GsonFactory.class),
        ConnectorConfigurationUtil.getProperty(PROXY_FUNCTION_URL_ENV_NAME));
  }
```

When using Spring, the Property, but also potentially the beans, can also come from the Spring runtime, see https://github.com/camunda-community-hub/spring-zeebe/tree/configurable-connectors/client/spring-zeebe/src/main/java/io/camunda/zeebe/spring/client/connector. This is set before any SPI bean is loaded: https://github.com/camunda-community-hub/spring-zeebe/blob/configurable-connectors/client/spring-zeebe/src/main/java/io/camunda/zeebe/spring/client/connector/ConnectorConfiguration.java#L27

If a connector does not use/implement those parameters, it still works, but is harder to configure via Spring. So we could (should?) make this way of configuration the default.

**Comment by berndruecker** [comment]
Let's say - this gives you a possibility to adjust certain objects you need internally. If you want to configure Gson differently in your runtime, you could do this now. 
I kind of agree that we would not need it today, but if Gson is not specific, it would be best practice to use the Spring provided one. 

I definitely see this coming down the line - but we could hold back the bean registry until we first need it, and let connectors configure /create all their beans on their own in the meantime. Just that it is impossible to adjust those objects (because of SPI) feels really bad...

**Comment by tmetzke** [comment]
My current issue with the registry and how we propose to use it here is that I can only see Connectors overwriting each others' instances of specific classes. But I don't see a concrete use case yet that this helps solve currently. But that might just be me missing something fundamental here.

**Comment by tmetzke** [comment]
One thing regarding SPIs: I think for Connector functions that should be fine. The Spring-based Connector runtime can still consume them but also provide other means (like Spring beans) to create them if that is helpful. And non-Spring runtime will also be able to consume them.
For other SDK components/classes that rely on SPIs (like the `ConnectorJobHandler` for secret providers) I see two opportunities:
1. Provide different constructors, one for injecting all dynamic members and one that picks them up via SPIs. Every runtime can decide how it wants the job handler to get those things (provide them via constructor or have the handler fetch them itself).
2. Allow subclassing and overriding the getters for those dynamic members (by default via SPI mechanism) so runtimes can specialize this if necessary.

I don't see how this should block us or make something more specialized like a bean registry necessary.
For the Connector functions, we currently don't encourage using something specific like GSON as provided by the environment because then we also need to make sure and clear that this is something a runtime needs to provide. People writing their own runtimes then need to know that this is something that they need to provide.

**Comment by berndruecker** [comment]
Let's postpone any discussion until we hit the problem. I set this to fixed now as we can now configure properties properly :-) All PR's merged.
