### ISSUE TITLE
Examine if we want to make `ZeebeClient` available in OutboundConnectorContext

### ISSUE THREAD

**Issue by berndruecker** [camunda/connector-sdk#273]
__Is your feature request related to a problem? Please describe.__

When @pierre-yves-monnet worked on a `SendBpmnMessageConnector` he wanted to send a BPMN message to the current Zeebe engine. Therefore he needs the ZeebeClient which is not yet available.

__Describe the solution you'd like__

Have the `ZeebeClient` available in InboundConnectorContext (or some other way to get it)

**Comment by pierre-yves-monnet** [comment]
Here is the project:
https://github.com/camunda-community-hub/camunda-8-connector-sendBPMNmessage/blob/main/src/main/java/io/camunda/connector/SendBPMNMessageFunction.java

**Comment by tmetzke** [comment]
Not sure this makes sense from a Connectors standpoint. 

If I build a Connector that should make calls to Slack, I need to create a Slack client in my Connector. If I want to make calls to a Zeebe engine, I need to create a Zeebe client in my Connector. Not sure we should simply hand over the client we (might) have in the runtime executing the Connector.

What happens when I run my Connector function in C7? There is no Zeebe client to hand into the Connector. This makes Connectors runtime-specific. I think that does not make much sense regarding the current idea of Connectors.

**Comment by tmetzke** [comment]
Not sure, I think it makes more sense to build a general "send BPMN Message" Connector that can send a message to whatever cluster. I can abstract from my own cluster by creating a specific element template with hardwired values for that if I need that. That way, I can reuse the Connector for all use cases and it's a lot more valuable. Plus, it's way more in line with what we consider a Connector (highly reusable with different configurations, environment-agnostic).

**Comment by pierre-yves-monnet** [comment]
I totally understand your approach. 

But on the other hand, my connector is only for C8. I call the Zeebe API to send the BPMN message,

So:
* is that acceptable for you to have a method "setZeebeClient()" in my connector? Then the framework can call it if he wants

* in order to simplify the configuration, I would love to give these options:
**Option A:** use the local Camunda Connection (then I need to have in the _context_ the Zeebe client - it may be null if the connector is executed in a different environment)
**Option B**: define a Zeebe connection to a Saas, asking four parameters ( clusterID... )
**Option C:** define a Zeebee connection to a Self-managed Zeebe (address)

If I implement Options A (via the use of the setZeebeeClient() approach), B, and C, is that acceptable for you to accept my connector in the club?

**Comment by tmetzke** [comment]
> my connector is only for C8

I honestly think we shouldn't go in such a direction with Connectors. If you want to build something really specific to C8 with the current APIs, it's better to just provide a job worker. Job workers are fine and still valid. Not everything has to be a Connector.

If this is supposed to be a Connector, it should follow the principles. Otherwise, we're building environment-specific things into the Connector SDK and every Connector has to state in which environments it actually works. That will lead to a total mess.

So, in my opinion, **Option A** is not possible with a Connector. Building such things into the SDK for corner cases like this will make Connectors become almost indistinguishable from job workers really fast. That will not help the overall story of Connectors, if you ask me.

Overall, I think sending messages inside the cluster I am currently working in (which is the use case I assume is needed for handing the Zeebe client into the Connector?) might also simply be a feature of the engine itself, without involving a Connector in the first place. If I want to send something to an EXTERNAL SYSTEM (i.e. different cluster), I can use a SendMessage Connector that needs connection information of course as described in **Option B** and **Option C.**

@MoAtCamunda, happy for more opinions here.

**Comment by nikku** [comment]
@tmetzke What feels like a connector ("element template") can very well be a plain job worker under the hood. And it should be fairly straight forward to build a Zeebe run-time behavior, powered by a job worker that connects to a remote Zeebe instance ("option B-C"), or re-uses the existing context.

From the users point of view we can still call it a "connector", because the only thing different is how it is being implemented (under the hood). Use case wise I believe this (and https://github.com/camunda/team-connectors/issues/84 respectively) make loads of sense (from the user perspective). 

I'd not jumping onto this (potential) solution too quickly though.

**Comment by nikku** [comment]
Just to sketch an alternative (to "talk to local zeebe"): Expose a secret that is being replaced with "local zeebe credentals", and allow that to be used within the connector.

GitHub actions does something similar where `GITHUB_TOKEN` is available for integrations, with very specific rights.

**Comment by MoAtCamunda** [comment]
My opinion is that we try to avoid any protocol (Zeebe/Camunda) specific attributes and make connectors as agnostic as possible. One of the differentiated values of Camunda connectors is that you dont have to be tied to Camunda specifics to create one. Write a function and go. Generally agree with @tmetzke and others - if you want that level of functionality, use job workers.

Caveat, based on PM understanding of the world.

**Comment by tmetzke** [comment]
> @tmetzke What feels like a connector ("element template") can very well be a plain job worker under the hood. And it should be fairly straight forward to build a Zeebe run-time behavior, powered by a job worker that connects to a remote Zeebe instance ("option B-C"), or re-uses the existing context.
> 
> From the users point of view we can still call it a "connector", because the only thing different is how it is being implemented (under the hood). Use case wise I believe this (and [camunda/team-connectors#84](https://github.com/camunda/team-connectors/issues/84) respectively) make loads of sense (from the user perspective).
> 
> I'd not jumping onto this (potential) solution too quickly though.

I actually think there are more things that differ here than the implementation under the hood. The installation journey, for example, is completely different for job workers and real Connectors. When we call it a Connector but in fact, it's a plain job worker, people cannot install it the same way (just add it to the Connector Runtime and you're good). We should therefore be careful about what we call a Connector that is supported by the SDK way of using Connectors.

**Comment by nikku** [comment]
> I actually think there are more things that differ here than the implementation under the hood. 

I agree. What I was referring to was the modeling user perspective. And there both shall not be "distinguishable".

**Comment by tmetzke** [comment]
> I agree. What I was referring to was the modeling user perspective. And there both shall not be "distinguishable".

Absolutely, yes.

**Comment by tmetzke** [comment]
I am closing this here for now as I don't think we should build something like this in the SDK. Happy to be proven wrong here 🙂
